### ISSUE TITLE
need an example

### ISSUE THREAD

**Issue by wesselah** [jdomeij/node-red-contrib-node-lifx#13]
could you please add the node red example ? 
I would like to see how you did it 
It seems that i can't get it right
I can only get the lifx bulbs  to on and off
every other string i sent does not work
i tried 
{
  "payload": {
    "on": true, 
    "bri": 77,
    "duration": 10000
  }
}

as an input but does not work

**Comment by jdomeij** [comment]
Simple example:
Create inject node, change type to JSON and add the following string
``{ "on": true, "hue": 100, "bri": 44, "duration": 3000 }``
connect this to the light and deploy.
This should change the light to green over 3s
