### ISSUE TITLE
No lights detected

### ISSUE THREAD

**Issue by jhelmink** [jdomeij/node-red-contrib-node-lifx#15]
So I've deployed an unconfigured node-lifx-in node with the Lifx Server set as per documentation.
But I still always get a 'No lights found' error.

I've also tried specifying the IP addresses in the Hub configuration, though I'm not sure exactly the format this is expecting? I've just put one light so far on a know (static) IP address (just putting 198.168.1.210 into the field - should this be a comma separated list?). But still no lights found.

Any ideas? My Lifx lights work via the phone app or Home Assistant, so they are discoverable on my network.

**Comment by jdomeij** [comment]
This sounds like an network problem, there is an simple js program ``examples/dump_lights.js`` in the project folder that can be used to debug the network traffic.
Enabling debug in the ``client.init`` section allows you to see if you get any network packets

**Comment by jhelmink** [comment]
Hmm I'm running Node Red inside a Docker Container on a Synology NAS in Host mode so it should have access to my network. I'll try using NodeJS to run `dump_lights.js` and see what I can find.

**Comment by jhelmink** [comment]
I'm now controlling my Lifx lights via Home Assistant so no longer need this palette. I'm going to assume it's something strange about my set up using Synology Docker.
